name: Lite Thinking QA TestOps Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

    
jobs:
  run-automation-suite:
    name: Ejecución de Pruebas y Reporte
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar Código del Repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar Entorno Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 3. Levantar Infraestructura de Kafka (Docker)
        run: |
          docker compose up -d --build
          echo "Esperando que Kafka-Broker esté completamente inicializado..."
          sleep 15

      - name: 4. Instalar Dependencias de Pruebas (Playwright)
        run: |
          # 🔍 Busca dinámicamente la carpeta que contiene el package.json
          TARGET_DIR=$(dirname $(find . -name "package.json" -not -path "*/node_modules/*" | head -n 1))
          echo "Proyecto encontrado en la ruta: $TARGET_DIR"
          
          # Entra a la carpeta e instala todo de forma segura
          cd "$TARGET_DIR"
          npm install --no-package-lock
          npx playwright install --with-deps

      - name: 5. Ejecutar Pruebas Playwright
        run: |
          # 🔍 Busca dinámicamente la carpeta para ejecutar los tests
          TARGET_DIR=$(dirname $(find . -name "package.json" -not -path "*/node_modules/*" | head -n 1))
          cd "$TARGET_DIR"
          npm run test

      - name: 6. Guardar Reporte de Playwright (Opcional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: "**/playwright-report/"
          retention-days: 7